// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace 电梯编码预处理
{
    public partial class TEST
    {
        /// <summary>
        /// model input class for TEST.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"ID")]
            public float ID { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"1")]
            public float _1 { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"2")]
            public float _2 { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"3")]
            public float _3 { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"4")]
            public float _4 { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"5")]
            public float _5 { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"6")]
            public float _6 { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"7")]
            public float _7 { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"8")]
            public float _8 { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"9")]
            public string _9 { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for TEST.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"ID")]
            public float ID { get; set; }

            [ColumnName(@"1")]
            public float _1 { get; set; }

            [ColumnName(@"2")]
            public float _2 { get; set; }

            [ColumnName(@"3")]
            public float _3 { get; set; }

            [ColumnName(@"4")]
            public float _4 { get; set; }

            [ColumnName(@"5")]
            public float _5 { get; set; }

            [ColumnName(@"6")]
            public float _6 { get; set; }

            [ColumnName(@"7")]
            public float _7 { get; set; }

            [ColumnName(@"8")]
            public float _8 { get; set; }

            [ColumnName(@"9")]
            public uint _9 { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("TEST.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
